// let a : string;
// let b : number;
// let c : boolean;
// let d : any;
// a = "hello world";
// b = 22;
// c = true;
// console.log(a);
// console.log('naber');
// console.log(b);
// console.log(a,b);
// console.log(a,b,c);
// console.log('d');
var langs;
langs = ["php", "java", "c++", "python"];
console.log(langs);
